# Domain layer - aggregates, events, value objects

from .channel import (
    ChannelAggregate,
    EntityNotFoundError,
    InvalidStateError,
)
from .content import (
    Approval,
    Attribution,
    DecisionContent,
    DecisionType,
    IssueType,
    JiraLink,
    Modification,
    Objection,
    ObjectionStatus,
    WorkItemContent,
)
from .entities import (
    ApprovedEntity,
    CommittedEntity,
    DeprecatedEntity,
    DraftEntity,
    Entity,
    EntityContent,
    ProposedEntity,
    get_lifecycle,
)
from .transitions import (
    TransitionError,
    add_approval,
    approve,
    can_approve,
    can_commit,
    can_modify,
    commit,
    deprecate,
    has_active_objections,
    propose,
    raise_objection,
    resolve_objection,
    withdraw_objection,
)
from .types import (
    ChannelId,
    EntityId,
    EntityLifecycle,
    EntityType,
    JiraKey,
    SyncStatus,
    ThreadTs,
    UserId,
    Version,
)

__all__ = [
    # Types
    "ChannelId",
    "EntityId",
    "EntityLifecycle",
    "EntityType",
    "JiraKey",
    "SyncStatus",
    "ThreadTs",
    "UserId",
    "Version",
    # Content
    "Approval",
    "Attribution",
    "DecisionContent",
    "DecisionType",
    "IssueType",
    "JiraLink",
    "Modification",
    "Objection",
    "ObjectionStatus",
    "WorkItemContent",
    # Entities
    "ApprovedEntity",
    "CommittedEntity",
    "DeprecatedEntity",
    "DraftEntity",
    "Entity",
    "EntityContent",
    "ProposedEntity",
    "get_lifecycle",
    # Transitions
    "TransitionError",
    "propose",
    "add_approval",
    "raise_objection",
    "resolve_objection",
    "withdraw_objection",
    "approve",
    "commit",
    "deprecate",
    "can_approve",
    "can_commit",
    "can_modify",
    "has_active_objections",
    # Channel aggregate
    "ChannelAggregate",
    "EntityNotFoundError",
    "InvalidStateError",
]
